timepad_url: "https://cu-events.timepad.ru"
events:
  - name: "Психолог Лилия Павлова"
    name_r: "Психолога Лилии Павловой"
    id: 3558805
    magic_string: "19107501836029767397"
  - name: "Психолог Светлана Шутькова"
    name_r: "Психолога Светланы Шутьковой"
    id: 3219855
    magic_string: "19105642996363502282"
