events:
  - name: "Психолог Лилия Павлова"
    id: 3558805
    url: "https://cu-events.timepad.ru/event/3558805/"
  - name: "Психолог Светлана Шутькова"
    id: 3219855
    url: "https://cu-events.timepad.ru/event/3219855/"
