version: '3.8'

services:
  app:
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER}/${IMAGE_NAME}:latest
    container_name: cu-timepad-bot-app
    restart: always
    environment:
      - MONGO_URI=mongodb://root:${MONGODB_PASSWORD}@mongodb:27017/
      - BOT_TOKEN=${BOT_TOKEN}
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: cu-timepad-bot-mongodb
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
    driver: local
