services:
  app:
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER}/${IMAGE_NAME}:latest
    container_name: cu-timepad-bot-app
    restart: unless-stopped
    environment:
      - MONGODB=mongodb://root:${MONGODB_PASSWORD}@mongodb:27017/
      - BOT_TOKEN=${BOT_TOKEN}
      - LOG_LEVEL=${LOG_LEVEL}
      - PROXY_URL=${PROXY_URL}
      - TELEGRAM_API_URL=${TELEGRAM_API_URL}
    volumes:
      - ./config.yaml:/config.yaml
    depends_on:
      - mongodb
      - redis

  redis:
    image: redis:latest
    container_name: cu-timepad-bot-redis
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_ARGS=--requirepass ${REDIS_PASSWORD} --appendonly yes
    volumes:
      - redis_data:/data

  mongodb:
    image: dburszty/mongodb-raspberrypi:7.0.14
    container_name: cu-timepad-bot-mongodb
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
    volumes:
      - mongo_data:/data/db

  # xray:
  #   image: teddysun/xray:latest
  #   container_name: cu-timepad-bot-xray
  #   restart: unless-stopped
  #   volumes:
  #     - "./xray.conf:/etc/xray/config.json"

volumes:
  mongo_data:
    driver: local
